### ISSUE TITLE
home page with masonry

### ISSUE THREAD

**Issue by harshil1712** [harshil1712/mozguj#3]
![Home](https://user-images.githubusercontent.com/18901032/59966936-b2b28400-9540-11e9-9a3b-3dd8962f0b68.jpeg)

**Comment by harshil1712** [comment]
@pransh15 I tried using masonry but there's an issue with that. All the images will have same dimensions. Won't be able to style images individually since all the images are called from the GraphQL query. A solution for this is to use CSS grid.
@Amorpheuz

**Comment by obitodarky** [comment]
Or we could use edited photos.

**Comment by harshil1712** [comment]
Yes that might work. But every time we will have to edit the photos to add it on the page.

**Comment by obitodarky** [comment]
I think we could write a small code for that.

**Comment by harshil1712** [comment]
That's a bit tricky

```
query IndexQuery {
    allImagesJson {
      edges {
        node {
          id
          title
          image {
            id
            childImageSharp {
              fixed(width: 300) {
                src
                ...GatsbyImageSharpFixed
              }
            }
          }
          caption
        }
      }
    }
  }
```

the above is the query that is fetching the images

and below is the masonry component code

```
  <Layout>
    <Masonry>
      {data.allImagesJson.edges.map(({ node }) => (
        <div key={node.id}>
          <Img fixed={node.image.childImageSharp.fixed} />
        </div>
      ))}
    </Masonry>
  </Layout>
```

Since we are getting images through the query, I am not sure how we can work with the sizes.
There is one way to do that, although not the best way, with the image data we can also send the size we want the image to be rendered in and pass this to the image

**Comment by Amorpheuz** [comment]
![image](https://user-images.githubusercontent.com/22113778/59967261-3a01f680-9545-11e9-9a81-7fcbdb61944b.png)
Won't a similar approach solve image sizing? 

I don't think we need to edit images (for bringing subject into focus).... building a component for something that can be done locally by the person who uploads the blog with images seems like over-engineering something. Though I don't mind switching over to CSS grid if that's what people are comfortable with.

**Comment by obitodarky** [comment]
> 
> 
> That's a bit tricky
> 
> ```
> query IndexQuery {
>     allImagesJson {
>       edges {
>         node {
>           id
>           title
>           image {
>             id
>             childImageSharp {
>               fixed(width: 300) {
>                 src
>                 ...GatsbyImageSharpFixed
>               }
>             }
>           }
>           caption
>         }
>       }
>     }
>   }
> ```
> 
> the above is the query that is fetching the images
> 
> and below is the masonry component code
> 
> ```
>   <Layout>
>     <Masonry>
>       {data.allImagesJson.edges.map(({ node }) => (
>         <div key={node.id}>
>           <Img fixed={node.image.childImageSharp.fixed} />
>         </div>
>       ))}
>     </Masonry>
>   </Layout>
> ```
> 
> Since we are getting images through the query, I am not sure how we can work with the sizes.
> There is one way to do that, although not the best way, with the image data we can also send the size we want the image to be rendered in and pass this to the image

What I am suggesting is that why not let graphql take the edited image itself. First a normal sized image would get edited and that is what graphql will take.

**Comment by obitodarky** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/22113778/59967261-3a01f680-9545-11e9-9a81-7fcbdb61944b.png)
> Won't a similar approach solve image sizing?
> 
> I don't think we need to edit images (for bringing subject into focus).... building a component for something that can be done locally by the person who uploads the blog with images seems like over-engineering something. Though I don't mind switching over to CSS grid if that's what people are comfortable with.

Can you test it out on random photos from past events and see how they work out?

**Comment by harshil1712** [comment]
@Amorpheuz the solution you suggested also has the same issue as I mentioned above, since the Img component is built for each image similarly we can't have different styles for them. We will have to call each image separately and style that component

**Comment by harshil1712** [comment]
> What I am suggesting is that why not let graphql take the edited image itself. First a normal sized image would get edited and that is what graphql will take.

GraphQL only queries the data. Since through a single query I am calling all the photos, I am not sure how we will do it for each image separately.

**Comment by obitodarky** [comment]
> 
> 
> > What I am suggesting is that why not let graphql take the edited image itself. First a normal sized image would get edited and that is what graphql will take.
> 
> GraphQL only queries the data. Since through a single query I am calling all the photos, I am not sure how we will do it for each image separately.

We can edit all the photos and then let graphql do the rest. Are we randomly setting the images in the page (In that case my solution won't work)?

**Comment by Amorpheuz** [comment]
Oh I see your point now, in that case... If we want to target specific images with specific dimensions, CSS grid or calling each image separately sounds like the only option. If its for styling purpose only, one could hack it with a code that adds class(for-styling) based on order.

**Comment by harshil1712** [comment]
> > > What I am suggesting is that why not let graphql take the edited image itself. First a normal sized image would get edited and that is what graphql will take.
> > 
> > 
> > GraphQL only queries the data. Since through a single query I am calling all the photos, I am not sure how we will do it for each image separately.
> 
> We can edit all the photos and then let graphql do the rest. Are we randomly setting the images in the page (In that case my solution won't work)?

We can sort the images, so that won't be an issue

**Comment by harshil1712** [comment]
@Amorpheuz I am storing the data in JSON right now. The information is basically, title, caption and the image source. We can add the size we want to render, and pass it to the component, not sure if this would work, but this is something that we can try.

**Comment by harshil1712** [comment]
@obitodarky @Amorpheuz understood what is going on. All the images are of same height, so we aren't getting the expected result. We will have to edit the photos, set their dimensions and then, I guess, this will solve our problem.

**Comment by pransh15** [comment]
What if we set a CSS for every img that we are to upload, from scratch. Once we have the layout, we can simply put in the images and we'll be ready to go?

I think we'll be able to crop the pictures accordingly whenever we need to highlight them on the homepage.

**Comment by harshil1712** [comment]
@pransh15 are you suggesting that we don't use masonry, or we just style the images for their heights and widths? Anyways, we'll have to call each image separately to assign them that particular style. 

I had to crop the images to achieve the below result
![Screenshot from 2019-06-23 00-29-26](https://user-images.githubusercontent.com/18901032/59980125-e78d0c80-960e-11e9-85d8-b31e7ef1b7cd.png)

**Comment by pransh15** [comment]
If we can't really control the layout with masonry - it would make the single screen layout difficult for us to control, more so would look really messy.

**Comment by obitodarky** [comment]
> @pransh15 are you suggesting that we don't use masonry, or we just style the images for their heights and widths? Anyways, we'll have to call each image separately to assign them that particular style.
> 
> I had to crop the images to achieve the below result
> ![Screenshot from 2019-06-23 00-29-26](https://user-images.githubusercontent.com/18901032/59980125-e78d0c80-960e-11e9-85d8-b31e7ef1b7cd.png)

We'll edit/crop the pictures. I don't think it should be a big deal.
