### ISSUE TITLE
Implement Container and Bootstrap grid throughout page

### ISSUE THREAD

**Issue by Amorpheuz** [harshil1712/mozguj#62]
**Is your feature request related to a problem? Please describe.**
Yes. Currently, the `container` and `container-fluid` class is being used on a granular level for individual sections which isn't actually required.

Even though the site feels responsive currently, it will allow the website to be fully responsive in all the cases including many edge-ones due to correct usage and the scenarios being tested out by the Bootstrap community.

**Describe the solution you'd like**
It would be a correct use of the Bootstrap Layout functionality if the correct `container` class is applied throughout the index page. Personally I would recommend `container-lg` and remove all the redundant nested containers.

Next, implement the `row` and `col` classes on each level with divs. I would love to see an in-depth conversation about grid implementations before it is finalized!

**Additional context**
More information can be found here: 
- https://getbootstrap.com/docs/4.4/layout/overview/
- https://getbootstrap.com/docs/4.4/layout/grid/

**Comment by JD235** [comment]
Assign this task to me will work on it.
