### ISSUE TITLE
Switch to Bootstrap spacing utilities for Padding and Margins

### ISSUE THREAD

**Issue by Amorpheuz** [harshil1712/mozguj#65]
**Is your feature request related to a problem? Please describe.**
Current website spacing is based on pixels which can lead to loss of responsiveness in case of a user having non-standard font sizes set for browsers. It also doesn't allow us to customize the spacing based on the size of the viewport.

**Describe the solution you'd like**
Switch all margin and padding calls to [Spacing Utilities](https://getbootstrap.com/docs/4.4/utilities/spacing/)!

**Describe alternatives you've considered**
- Perform manual spacing in terms of `rem`.

**Comment by JD235** [comment]
assign it to me will work on it.
